apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xx
subjects:
- kind: User
  name: xx-username
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: xx-group
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: xx-sa
  apiGroup: rbac.authorization.k8s.io
roleRef:
  name: xx
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
