apiVersion: v1
kind: Pod
metadata:
  name: string
  labels:
    app: string
spec:
  containers:
    - name: string
      image: string
      volumeMounts:
        - name: string
          mountPath: string  # 挂载目录，绝对路径
          readOnly: boolean  # 默认false

  # 存储卷
  volumes:
    - name: string
      emptyDir: {}
    - name: string
      hostPath:
        path: /the/path
    - name: string
      secret:
        secretName: string
        items:
          - key: string
            path: string
    - name: string
      configMap:
        name: string
        items:
          - key: string
            path: string
